### ISSUE TITLE
Непонятности с уведомлениями

### ISSUE THREAD

**Issue by esuslik** [southbridgeio/redmine_intouch#104]
В телеграм приходит много уведомлений по одной и тойже задаче. Хотя над ней не выполняются никакие действия и в настройках не стоят галочки о мнгновенных уведомлениях.

Сообщения приходят раз в минуту или чаще или позже, как-то хаотично.
В периодических уведомлениях настроены только уведомления для статусов не назначена и просрочено.
Задача по которой идут обновления не подпадает ни под одно условие для уведомлений и по крону выставлены периоды каждые 30 и 45 минут. А фигачит каждую минуту.

В sidekiq вижу такую картину, может это связано:

  | Next Retry | Retry Count | Queue | Job | Arguments | Error
-- | -- | -- | -- | -- | -- | --
  | in 22 seconds | 2 | default | LiveHandlerWorker | 192363 | NoMethodError: private method `select' called for nil:NilClass
  | in 54 seconds | 2 | default | LiveHandlerWorker | 192364 | NoMethodError: private method `select' called for nil:NilClass
  | in 1 minute | 2 | default | LiveHandlerWorker | 192362 | NoMethodError: private method `select' called for nil:NilClass
  | in 2 minutes | 3 | default | EmailLiveSenderWorker | 59096, nil, nil | NoMethodError: undefined method `each' for nil:NilClass
  | in 8 minutes | 5 | default | EmailLiveSenderWorker | 59095, nil, nil | NoMethodError: undefined method `each' for nil:NilClass
  | in 8 minutes | 5 | default | LiveHandlerWorker | 192359 | NoMethodError: private method `select' called for nil:NilClass

**Comment by funk-yourself** [comment]
У вас используется шаблон настроек intouch или индивидуальные настройки для проекта?
Почему-то настройки протоколов уведомлений возвращают nil, из-за этого всё дальше и валится.
Возможно, поможет пересохранение настроек проекта.

**Comment by esuslik** [comment]
Используется один шаблон и он подключен во всех проектах

**Comment by esuslik** [comment]
Пересохранил настройки в каждом проекте. Вроде как заработало нормально. В sidekiq остались только такие ошибки:

in 2 minutes | 3 | default | LiveHandlerWorker | 192485 | NoMethodError: private method `select' called for nil:NilClass
-- | -- | -- | -- | -- | --
  | in 3 minutes | 4 | default | LiveHandlerWorker | 192483 | NoMethodError: private method `select' called for nil:NilClass
  | in 5 minutes | 4 | default | LiveHandlerWorker | 192484 | NoMethodError: private method `select' called for nil:NilClass

**Comment by esuslik** [comment]
Всетка проблема не устранена. Все также уведомления валят в телеграм хаотично. В sidekiq также пачка сообщений во вкладке retries

**Comment by esuslik** [comment]
Создал новый шаблон, прописал в нем настройки по новой. Выставил данный шаблон для проектов. Проблема повторяется.

  | Next Retry | Retry Count | Queue | Job | Arguments | Error
-- | -- | -- | -- | -- | -- | --
  | in 31 seconds | 5 | default | EmailLiveSenderWorker | 59361, nil, nil | NoMethodError: undefined method `each' for nil:NilClass

**Comment by funk-yourself** [comment]
Смержил исправления в master. Старые попытки лучше удалить в sidekiq.

**Comment by esuslik** [comment]
после обновления в логах также на вкладке retries появляются ошибки

  | in 3 minutes | 5 | default | EmailLiveSenderWorker | 59589, 194232, nil | NoMethodError: undefined method `each' for nil:NilClass
-- | -- | -- | -- | -- | -- | --
  | in 17 minutes | 7 | default | EmailLiveSenderWorker | 59587, 194230, nil | NoMethodError: undefined method `each' for nil:NilClass
  | in 20 minutes | 7 | default | EmailLiveSenderWorker | 59588, 194229, nil | NoMethodError: undefined method `each' for nil:NilClass

**Comment by funk-yourself** [comment]
А сайдкик точно перезапустили? После исправления третьим аргументом не должно передаваться nil

**Comment by esuslik** [comment]
перезапустил сайдкик, теперь все ок, во вкладке retries пусто
