### ISSUE TITLE
Проблемы с WedHooks

### ISSUE THREAD

**Issue by lDerretl** [southbridgeio/redmine_intouch#112]
Добрый день!
Помогите, пожалуйста, разобраться в чем может быть проблема:
Авторизовал клиента telegram, в плагине redmine intouch все заполнено:
![image](https://user-images.githubusercontent.com/44054314/47837486-37d40780-ddbd-11e8-9b37-25602b888229.png)
Версии:
![image](https://user-images.githubusercontent.com/44054314/47837507-4e7a5e80-ddbd-11e8-9f7a-d767c7c450df.png)
sidekiq\redis работают. 
Redmine работает через ssl, доступ в интернет есть. При нажатии на "Инициализировать бота" ошибка в логах:
![image](https://user-images.githubusercontent.com/44054314/47837557-94372700-ddbd-11e8-8462-d96d8de47df1.png)
Пробовал запустить через : https://api.telegram.org/bot_TOKEN/setwebhook?url=https://MY_IP/settings/plugin/redmine_bots?tab=telegram
Выдало: 
![image](https://user-images.githubusercontent.com/44054314/47837661-e1b39400-ddbd-11e8-8d4f-b49a40596fcb.png)

Сам бот не реагирует на команду /start.

Подскажите, в чем может быть проблема?

**Comment by funk-yourself** [comment]
Добрый день!

http-клиент, используемый в геме telegram-bot-ruby не может подключиться к api.telegram.org. С РКН точно проблем нет на сервере? Telegram не блокируется?

**Comment by lDerretl** [comment]
Каких именно проблем на сервере?
телеграмм не блокируется

**Comment by lDerretl** [comment]
И правда блокировка телеграмм у меня на сервере. 
Можете подсказать, как ее обойти?

**Comment by funk-yourself** [comment]
В настройках плагина redmine_bots можно задать http-прокси для бота. Либо подключаться через VPN.
