### ISSUE TITLE
Не отправляет уведомления.

### ISSUE THREAD

**Issue by Mikhail29** [southbridgeio/redmine_intouch#120]
Здравствуйте! 
Вот такая информация о redmine:
`Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_bots                   0.3.1
  redmine_intouch                1.4.0
  redmine_sidekiq                2.1.0`

на /start среагировал, на /connect сработало, в бд создало запись с данными о телеграм и ответ пришёл что всё связано, но уведомления не приходят. Вот такой ответ идёт в провалах sidekiq:
`ActionView::Template::Error: undefined method `default_url_options' for ActionMailer::Parameterized::Mailer:Class`
 в логе вот такое:
`I, [2019-07-18T02:41:17.450509 #463]  INFO -- : start
D, [2019-07-18T02:41:17.451988 #463] DEBUG -- : enqueued schedule: {"class":"TelegramLiveSenderWorker","args":[13,50,[1]],"retry":true,"queue":"default","jid":"0e7c5344e71b5b39921f42f0","created_at":1563406868.734719}
I, [2019-07-18T02:41:17.453351 #463]  INFO -- : start
D, [2019-07-18T02:41:17.457433 #463] DEBUG -- : enqueued schedule: {"class":"TelegramGroupLiveSenderWorker","args":[13,50],"retry":true,"queue":"default","jid":"0775c779c5bb81fe9b0a612f","created_at":1563406868.7496245}
I, [2019-07-18T02:41:17.504470 #463]  INFO -- : done: 0.051 sec
E, [2019-07-18T02:41:17.642226 #463] ERROR -- : Error fetching job: ERR value is not an integer or out of range
W, [2019-07-18T02:41:17.642341 #463]  WARN -- : Redis::CommandError: ERR value is not an integer or out of range
W, [2019-07-18T02:41:17.642417 #463]  WARN -- : ....rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:156:in `value'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:148:in `_set'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:75:in `block in finish'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:74:in `each'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:74:in `each_with_index'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:74:in `each'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:74:in `map'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:74:in `finish'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/pipeline.rb:98:in `finish'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/client.rb:164:in `block in call_pipeline'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/client.rb:306:in `with_reconnect'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis/client.rb:162:in `call_pipeline'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis.rb:2462:in `block in multi'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize'
..../.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize'
..../.rvm/gems/ruby-2.4.6/gems/redis-4.1.2/lib/redis.rb:2454:in `multi'
..../.rvm/gems/ruby-2.4.6/gems/redis_rate_limiter-0.1.0/lib/redis_rate_limiter.rb:35:in `add'
..../.rvm/gems/ruby-2.4.6/bundler/gems/sidekiq-rate-limiter-d95520ad60cb/lib/sidekiq-rate-limiter/fetch.rb:40:in `block in limit'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq.rb:97:in `block in redis'
..../.rvm/gems/ruby-2.4.6/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
..../.rvm/gems/ruby-2.4.6/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
..../.rvm/gems/ruby-2.4.6/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
..../.rvm/gems/ruby-2.4.6/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
..../.rvm/gems/ruby-2.4.6/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq.rb:94:in `redis'
..../.rvm/gems/ruby-2.4.6/bundler/gems/sidekiq-rate-limiter-d95520ad60cb/lib/sidekiq-rate-limiter/fetch.rb:34:in `limit'
..../.rvm/gems/ruby-2.4.6/bundler/gems/sidekiq-rate-limiter-d95520ad60cb/lib/sidekiq-rate-limiter/fetch.rb:12:in `retrieve_work'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:89:in `get_one'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:99:in `fetch'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:82:in `process_one'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
..../.rvm/gems/ruby-2.4.6/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'`

К сожалению я больше специализируюсь на php на ruby on rails всё что мог сделал, больше без помощи не смогу сделать и определить в чём ошибка тоже, так что надеюсь на вашу помощь...

**Comment by gen555** [comment]
Для нового редмайн надо пропатчить app/models/intouch_mailer.rb на 12й строке:
было:
Mailer.default_url_options

стало:
::Mailer.default_url_options

Иначе ошибка
" undefined method `default_url_options' for ActionMailer::Parameterized::Mailer:Class"
гарантирована.
