### ISSUE TITLE
Не смог заставить плагин высылать уведомления на Telegram / Slack

### ISSUE THREAD

**Issue by TonyNoIT** [southbridgeio/redmine_intouch#124]
Уточню сразу - установил все с нуля на сервере в Европе - результат такой же как и на сервере в РФ - блокировки не виноваты... )))

Исходные данные:
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redmine_bots                   0.3.1
  redmine_intouch                1.4.0
  redmine_sidekiq                2.1.0

Все под https:// в настройках хост указан ***.***.*** ниже выбрано https://
Sidekiq - запускается - задачи выполняются и попадают в Processed
Авторизация через телефон не делается - https://***/telegram/setup/step_2 все тоже самое Unknown error. Please, see TDlib logs. Пароля на аккаунте нет, но это и не важно, ведь он не дает поле куда вводить код подтверждения. При этом бот (webhook) совершенно спокойно авторизуется и активируется - работает - отвечает.
Из немаловажного - ваш плагин redmine_2fa - работает идеально - все уведомления в Telegram присылаются и никаких проблем
tdlib-ruby установил 2.1.0 - результат тот же

<img width="1132" alt="Screenshot 2020-01-03 at 00 37 17" src="https://user-images.githubusercontent.com/58567087/71699727-5074ee80-2dc1-11ea-9c5b-c858841a6e72.png">
<img width="1133" alt="Screenshot 2020-01-03 at 00 37 06" src="https://user-images.githubusercontent.com/58567087/71699728-5074ee80-2dc1-11ea-8b31-dc6340edcebd.png">
<img width="1012" alt="Screenshot 2020-01-03 at 00 36 49" src="https://user-images.githubusercontent.com/58567087/71699729-5074ee80-2dc1-11ea-8432-052e4354066d.png">
<img width="1298" alt="Screenshot 2020-01-03 at 00 36 17" src="https://user-images.githubusercontent.com/58567087/71699730-510d8500-2dc1-11ea-9d41-2ea7bc431803.png">
<img width="1301" alt="Screenshot 2020-01-03 at 00 36 02" src="https://user-images.githubusercontent.com/58567087/71699731-510d8500-2dc1-11ea-9e22-a067ebdcc2ad.png">
<img width="1302" alt="Screenshot 2020-01-03 at 00 35 51" src="https://user-images.githubusercontent.com/58567087/71699733-510d8500-2dc1-11ea-8799-d494f19cd821.png">
<img width="1301" alt="Screenshot 2020-01-03 at 00 35 39" src="https://user-images.githubusercontent.com/58567087/71699734-510d8500-2dc1-11ea-9c40-b37838fbb6c5.png">
<img width="806" alt="Screenshot 2020-01-03 at 00 31 34" src="https://user-images.githubusercontent.com/58567087/71699735-51a61b80-2dc1-11ea-9819-1d2728776756.png">
<img width="1115" alt="Screenshot 2020-01-03 at 00 20 17" src="https://user-images.githubusercontent.com/58567087/71699736-51a61b80-2dc1-11ea-8f40-683d2093a868.png">
<img width="1266" alt="Screenshot 2020-01-03 at 00 19 53" src="https://user-images.githubusercontent.com/58567087/71699737-523eb200-2dc1-11ea-9a33-52f9b872578a.png">

Ведь БОТ работает - сообщения отсылаются… По мне так это означает что проблема где-то на уровне кода - сообщения просто не генерируются для отправки ботом.

**Comment by funk-yourself** [comment]
Добрый день! Можете показать `log/redmine_bots/message-sender.log`, если он есть?

**Comment by TonyNoIT** [comment]
Добрый. А этого лога нет (((

**Comment by funk-yourself** [comment]
По логу live-checker-base вижу, что вы пишете комментарий в задаче с закрытым статусом. По таким задачам мгновенные уведомления не присылаются.

**Comment by TonyNoIT** [comment]
Да часть лога была скопирована наобум - поскольку я пробовал абсолютно любые манипуляции в задаче - видимо попала часть именно манипуляций с закрытой задачей.

**Comment by olemskoi** [comment]
Ошибка исправлена. Спасибо.
