### ISSUE TITLE
nameError

### ISSUE THREAD

**Issue by TitovNS** [southbridgeio/redmine_intouch#133]
Здравствуйте. 
После обновления c redmine 4.1.1 до 4.2.1 появилась ошибка: NameError: undefined local variable or method `users_by_role' for #<Project:0x00007f70edb59040>
Также при создании задачи в проекте, где используется redmine_intouch появляется Internal error, но задача создается. 
Проблема ушла после отключения плагина. 
Может быть подскажете куда смотреть? 
В логах только эту ошибку нашел.

**Comment by xziy** [comment]
Fixed 
https://github.com/southbridgeio/redmine_intouch/pull/135

**Comment by TitovNS** [comment]
thanks
