### ISSUE TITLE
Возможность работы плагина совместно с redmine_contacts_helpdesk

### ISSUE THREAD

**Issue by esuslik** [southbridgeio/redmine_intouch#71]
У нас стоит плагин redmine_contacts_helpdesk от redmineup.com
Данный плагин позволяет принимать задачи от неавторизованых в redmine пользователей и работать по их задачам.
В каждой задаче добавляется контакт обращения и в нем прописывается email автора который создал тикет.

Проблема в том что плагин intouch при настройке уведомления автору пытается отправить сообщение автору из стандартного поля, но там указан аноним.
Хотелось бы увидеть возможность указать из какого поля брать email автора, чтобы плагин заработал полноценно.

По роду своей деятельности 99% тикетов приходят именно от неавторизованых пользователей через email и rest api

**Comment by olemskoi** [comment]
Мы запланировали работу по вашему запросу. Но вряд ли получится быстро.

**Comment by esuslik** [comment]
ок, будем ждать. Не критичная задача.

**Comment by funk-yourself** [comment]
Добавили в последнем релизе #80

**Comment by esuslik** [comment]
Уведомления также уходять в стандартные контакты автора, то есть либо аноним либо пользователю который создает задачи через rest api. А должны уходить на адрес который прописан в задаче в плагине crm и helpdesk

**Comment by esuslik** [comment]
Еще нашел ошибку, если в настройках стоит уведомлять о не назначеных задачах на группу по email то по расписанию по крону уведомление уходит не пользователям редмайна которые находятся в группе, а клиенту который указан как автор(плагин helpdesk)

**Comment by esuslik** [comment]
После обновления, уведомления всеравно уходят клиенту вместо исполнителя.
Причем сейчас видимо где-то сохранились данные и даже если в настройках плагина вообще отключить все уведомления по email они всеравно уходят клиенту. Причем исполнителям не ходят, а клиенту приходят

**Comment by funk-yourself** [comment]
Речь об уведомлениях, которые уходят сразу при обновлении/создании задачи или о периодических уведомлениях?

**Comment by esuslik** [comment]
Периодические уведомления. Например не назначеные задачи уведомления падают клиенту на почту

**Comment by funk-yourself** [comment]
Попробуйте последнюю версию, пожалуйста. Обратите внимание на [этот](https://github.com/centosadmin/redmine_intouch#upgrade-from-12-to-13) пункт в README.
